name: Build C++ server app

on:
  push:
    paths:
      - main.cpp
      - .github/workflows/build.yml
  pull_request:
    paths:
      - main.cpp
      - .github/workflows/build.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install build essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build main.cpp
      run: |
        g++ main.cpp -o server_app

    - name: Save artifact (binary)
      uses: actions/upload-artifact@v4
      with:
        name: server_app
        path: server_app
